# AUTOGENERATED FROM 'common/queries/user/user_update.edgeql' WITH:
#     $ edgedb-py --tls-security=insecure -P 5656 -d precepto --dir ./common/queries


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserUpdateResult(NoPydanticValidation):
    id: uuid.UUID


async def user_update(
    executor: edgedb.AsyncIOExecutor,
    *,
    first_name: str | None = None,
    last_name: str | None = None,
    email: str | None = None,
    image_url: str | None = None,
    is_admin: bool | None = None,
    last_login: datetime.datetime | None = None,
    logged_in: bool | None = None,
    category: str | None = None,
    id: uuid.UUID,
) -> UserUpdateResult | None:
    return await executor.query_single(
        """\
        # Update a user's information
        UPDATE User
        FILTER .id = <uuid>$id
        SET {
            first_name := <optional str>$first_name,
            last_name := <optional str>$last_name,
            email := <optional str>$email,
            image_url := <optional str>$image_url,
            is_admin := <optional bool>$is_admin,
            last_login := <optional datetime>$last_login,
            logged_in := <optional bool>$logged_in,
            category := <optional str>$category
        };\
        """,
        first_name=first_name,
        last_name=last_name,
        email=email,
        image_url=image_url,
        is_admin=is_admin,
        last_login=last_login,
        logged_in=logged_in,
        category=category,
        id=id,
    )
