# AUTOGENERATED FROM 'common/queries/user/user_create.edgeql' WITH:
#     $ edgedb-py --tls-security=insecure -P 5656 -d precepto --dir ./common/queries


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UserCreateResult(NoPydanticValidation):
    id: uuid.UUID


async def user_create(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_name: str,
    first_name: str | None = None,
    last_name: str | None = None,
    email: str | None = None,
    image_url: str | None = None,
    login_pass: str,
    is_admin: bool,
    logged_in: bool | None = None,
    last_login: datetime.datetime | None = None,
    category: str | None = None,
) -> UserCreateResult:
    return await executor.query_single(
        """\
        INSERT User {
            user_name := <str>$user_name,
            first_name :=  <optional str>$first_name,
            last_name :=  <optional str>$last_name,
            email :=  <optional str>$email,
            image_url :=  <optional str>$image_url,
            login_pass := <str>$login_pass,
            is_admin := <bool>$is_admin,
            logged_in := <optional bool>$logged_in,
            last_login := <optional datetime>$last_login,
            category := <optional str>$category
        };\
        """,
        user_name=user_name,
        first_name=first_name,
        last_name=last_name,
        email=email,
        image_url=image_url,
        login_pass=login_pass,
        is_admin=is_admin,
        logged_in=logged_in,
        last_login=last_login,
        category=category,
    )
