# AUTOGENERATED FROM 'common/queries/auth/auth_token_delete.edgeql' WITH:
#     $ edgedb-py --tls-security=insecure -P 5656 -d precepto --dir ./common/queries


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AuthTokenDeleteResult(NoPydanticValidation):
    id: uuid.UUID


async def auth_token_delete(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> list[AuthTokenDeleteResult]:
    return await executor.query(
        """\
        # Delete a auth token by user ID
        DELETE AuthToken
        FILTER .user.id = <uuid>$user_id\
        """,
        user_id=user_id,
    )
