# AUTOGENERATED FROM 'common/queries/auth/auth_token_read.edgeql' WITH:
#     $ edgedb-py --tls-security=insecure -P 5656 -d precepto --dir ./common/queries


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AuthTokenReadResult(NoPydanticValidation):
    updated_at: datetime.datetime
    created_at: datetime.datetime
    id: uuid.UUID
    expires_at: datetime.datetime
    token: str
    user: AuthTokenReadResultUser


@dataclasses.dataclass
class AuthTokenReadResultUser(NoPydanticValidation):
    updated_at: datetime.datetime
    created_at: datetime.datetime
    id: uuid.UUID
    category: str
    email: str | None
    first_name: str | None
    image_url: str | None
    is_admin: bool | None
    last_login: datetime.datetime | None
    last_name: str | None
    logged_in: bool | None
    login_pass: str | None
    user_name: str


async def auth_token_read(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> list[AuthTokenReadResult]:
    return await executor.query(
        """\
        # Read a Token by User ID
        SELECT AuthToken  {**}
        FILTER .user.id = <uuid>$user_id;\
        """,
        user_id=user_id,
    )
