# AUTOGENERATED FROM 'common/queries/auth/auth_token_update.edgeql' WITH:
#     $ edgedb-py --tls-security=insecure -P 5656 -d precepto --dir ./common/queries


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AuthTokenUpdateResult(NoPydanticValidation):
    id: uuid.UUID


async def auth_token_update(
    executor: edgedb.AsyncIOExecutor,
    *,
    token: str,
    expires_at: datetime.datetime,
    user_id: uuid.UUID,
) -> list[AuthTokenUpdateResult]:
    return await executor.query(
        """\
        # Update a authtoken's details
        UPDATE AuthToken
        FILTER .user.id = <uuid>$user_id
        SET {
            token := <str>$token,
            expires_at := <datetime>$expires_at
        };\
        """,
        token=token,
        expires_at=expires_at,
        user_id=user_id,
    )
